name: Push Docker Image

on:
  push:
    branches:
      - master
      - main
      - stage
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login into Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Get Short SHA
        id: vars
        run: |
          echo ::set-output name=short_sha::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Build the Docker image
        run: |
          docker build --build-arg APP_ENV=production \
               --build-arg RUBY_VERSION=3.2.0 \
               --build-arg PG_MAJOR=11 \
               --build-arg NODE_MAJOR=16 \
               --build-arg YARN_VERSION=1.13.0 \
               --build-arg BUNDLER_VERSION=2.3.26 \
               -t ssangyongsports/logto:${{ steps.vars.outputs.short_sha }} \
               .

      - name: Tag and Push Docker image with SHA
        if: github.event_name == 'push'
        run: |
          docker push ssangyongsports/logto:${{ steps.vars.outputs.short_sha }}
          echo "Pushed Docker image with tag: ${{ steps.vars.outputs.short_sha }}"

      - name: Tag LATEST and Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag ssangyongsports/logto:${{ steps.vars.outputs.short_sha }} ssangyongsports/logto:latest
          docker push ssangyongsports/logto:latest
          echo "Pushed Docker image with tag: latest"

      - name: Tag RELEASE and Push Docker image
        if: github.event_name == 'release'
        run: |
          docker tag ssangyongsports/logto:${{ steps.vars.outputs.short_sha }} ssangyongsports/logto:${{ github.ref_name }}
          docker push ssangyongsports/logto:${{ github.ref_name }}
          echo "Pushed Docker image with tag: ${{ github.ref_name }}"
